version: '3.9'
services:
  backend:
    container_name: app_backend
    build: ./
    ports:
      - 3001:3001
    working_dir: /app-backend
    command: dev:server
    volumes:
      - ./src:/app-backend/src
